run:
  timeout: 3m
  modules-download-mode: readonly

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/fortunnels)
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/fortunnels
  govet:
    enable:
      - shadow
  dupl:
    threshold: 50
  funlen:
    lines: 120
    statements: 120
  gocyclo:
    min-complexity: 35
  lll:
    line-length: 200
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: true
  errcheck:
    check-type-assertions: true
    check-blank: true

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gci
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - dupl
        - errcheck
        - bodyclose
        - goconst
        - gosec
        - revive
        - gocritic
    - path: internal/config/flags\.go
      linters:
        - dupl
    - text: "exported.*should have comment"
      linters:
        - revive
    - text: "could not import sync/atomic"
      linters:
        - typecheck
  max-issues-per-linter: 0
  max-same-issues: 0
